spring:
  application:
     name: quotes-service
pivotal:
  quotes:
    quote_url: https://cloud.iexapis.com/v1/stock/{symbol}/quote/?token={token}
    quotes_url: https://cloud.iexapis.com/v1/stock/market/batch?symbols={symbols}&types=quote/?token={token}
    quotes_token: ${iex_token}
    companies_url: http://dev.markitondemand.com/MODApis/Api/v2/Lookup/json?input={name}
