spring:
  application:
     name: quotes-service
pivotal:
  quotes:
    quote_url: https://cloud.iexapis.com/v1/stock/{symbol}/quote/?token={token}
    quotes_url: https://cloud.iexapis.com/v1/stock/market/batch?symbols={symbols}&types=quote/?token={token}
    quotes_token: pk_6a68060d042a470297b98a2d240c3465
    companies_url: http://dev.markitondemand.com/Api/v2/Lookup/json?input={name}
